#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*               linuxserver/airsonic                 *
*                                                    *
*    https://hub.docker.com/r/linuxserver/airsonic   *
*                                                    *
*   https://github.com/linuxserver/docker-airsonic   *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
